### PR TITLE
Support is loading state & Pagination "load more"

### PR DESCRIPTION
**Pull request by i74ifa**
- A loading button has been added to display when waiting for the results to load.
- A load more button has been added to support pagination and load more search results.

[demo live](https://movies-nine-bice.vercel.app/)

### CODE REVIEW

**Comment by i74ifa** [comment]
Thank you

What modifications are needed to merge it into main repository

**Comment by Hidaya-M** [comment]
i didnt understand your question exactly cause iam new on github sorry i74aifa

**Comment by i74ifa** [comment]
ahaa ok
I was explaining what I meant by "merging my changes on GitHub"

I have submitted a request to merge the changes I made into this repository. You can request modifications to comply with your programming style or fix any errors, and then accept my merge request

"This is a link to the merge guide: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue


And finally, Hidaya, I'm not insisting on merging my changes 😂 I just wanted to explain to you when you said you didn't know. Thank you!"

**Comment by Hidaya-M** [comment]
i really like the changes you made, great job hothaifa !!!
and Thank you for taking the time to explain the merging process to me. I appreciate it

**Pull request closed without merging**
